services:
  database:
    container_name: loc_stream_db
    image: 'postgis/postgis:16-3.5'
    ports:
      - 15432:5432
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - ${PWD}/db-data/:/var/lib/postgresql/data/
    restart: unless-stopped
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 15433:80
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - postgres-network
    volumes:
      - ${PWD}/pgadmin-data/:/var/lib/pgadmin/
    restart: unless-stopped

networks: 
  postgres-network:
    driver: bridge